application: dnd-zgz
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static/

- url: /cache/
  static_dir: cache/
  expiration: '4d 5h'

- url: .*
  script: main.py
